In [1]:
import pandas as pd

In [3]:
df= pd.read_csv("C:\\Users\\amitm\\Downloads\\financial_dataset.csv")

In [5]:
# Quick look at data
print(df.shape)
print(df.info())
print(df.describe())
print(df.head())

(10000, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Age                           9500 non-null   float64
 1   Annual_Income                 9500 non-null   float64
 2   Monthly_Expenses              9500 non-null   float64
 3   Savings_Rate                  9500 non-null   float64
 4   Debt_to_Income_Ratio          9505 non-null   float64
 5   Current_Investments_Value     9500 non-null   float64
 6   Total_Loan_Amount             9500 non-null   float64
 7   Avg_Credit_Score              9500 non-null   float64
 8   Inflation_Rate                9500 non-null   float64
 9   Interest_Rate                 9500 non-null   float64
 10  Years_of_Employment           9500 non-null   float64
 11  Job_Stability_Score           9500 non-null   float64
 12  Emergency_Fund_Value          9500 non-null   float64
 13  Retirement_Fund_Contribution  9500 non-null   float64
 14  Customer_Segment              10000 non-null  object
 15  Future_Balance                10000 non-null  float64
dtypes: float64(15), object(1)
memory usage: 1.2+ MB
None
               Age  Annual_Income  Monthly_Expenses  Savings_Rate  \
count  9500.000000   9.500000e+03       9500.000000   9500.000000
mean     40.104000   1.069967e+06      47411.526088      0.286018
std       9.706598   1.063655e+06      28181.118502      0.158427
min      21.000000   3.000000e+05      10311.280000      0.000000
25%      33.000000   6.926435e+05      31632.887500      0.160000
50%      40.000000   9.093829e+05      41796.795000      0.270000
75%      47.000000   1.199309e+06      56158.172500      0.390000
max      65.000000   2.860215e+07     531037.550000      0.900000

       Debt_to_Income_Ratio  Current_Investments_Value  Total_Loan_Amount  \
count           9505.000000               9.500000e+03       9.500000e+03
mean               0.351678               2.274003e+06       8.485883e+05
std                0.244666               1.020151e+06       5.660434e+05
min                0.000000               4.065681e+05       7.906566e+04
25%                0.200000               1.500302e+06       4.609977e+05
50%                0.320000               2.088030e+06       7.074450e+05
75%                0.460000               2.855635e+06       1.063804e+06
max                2.000000               5.000000e+06       5.000000e+06

       Avg_Credit_Score  Inflation_Rate  Interest_Rate  Years_of_Employment  \
count       9500.000000     9500.000000    9500.000000          9500.000000
mean         666.307263        6.006605       7.035445             8.092389
std           43.635712        0.978770       1.467793             4.764537
min          499.000000        3.000000       4.000000             0.000000
25%          637.000000        5.350000       6.020000             4.600000
50%          667.000000        6.000000       7.000000             8.000000
75%          696.000000        6.650000       8.040000            11.400000
max          833.000000       10.000000      12.000000            26.900000

       Job_Stability_Score  Emergency_Fund_Value  \
count          9500.000000           9500.000000
mean              0.302957         226612.075007
std               0.153323         122452.335964
min               0.000000          34247.680000
25%               0.190000         141688.820000
50%               0.300000         199492.950000
75%               0.410000         279561.945000
max               0.920000        1000000.000000

       Retirement_Fund_Contribution  Future_Balance
count                   9500.000000    1.000000e+04
mean                   98428.157903    2.826334e+06
std                    50448.211821    1.203896e+06
min                    15219.190000    5.110349e+05
25%                    62337.455000    1.920633e+06
50%                    88130.220000    2.608302e+06
75%                   122811.030000    3.488464e+06
max                   416528.290000    7.461108e+06
    Age  Annual_Income  Monthly_Expenses  Savings_Rate  Debt_to_Income_Ratio  \
0  45.0      686081.81          17942.27          0.29                  0.25
1   NaN      796474.39          55385.20          0.12                  0.55
2  46.0      708707.11               NaN          0.29                  0.38
3  55.0      940641.40          55378.16          0.11                  0.18
4  38.0     1452826.39          74823.60          0.29                  0.75

   Current_Investments_Value  Total_Loan_Amount  Avg_Credit_Score  \
0                 1807462.47          556913.97             651.0
1                 2935502.53          563982.05             728.0
2                 1569022.45          479932.78             748.0
3                 3154348.23          484769.37             686.0
4                 4180505.40          839038.16             593.0

   Inflation_Rate  Interest_Rate  Years_of_Employment  Job_Stability_Score  \
0            6.69           6.65                  9.4                 0.39
1             NaN           8.25                 17.8                 0.50
2            6.14           7.33                  8.5                 0.44
3            6.04           5.70                 11.8                 0.35
4            5.48           7.91                  5.9                 0.37

   Emergency_Fund_Value  Retirement_Fund_Contribution Customer_Segment  \
0              67331.21                      98811.48           Bronze
1             298162.24                      42078.16           Silver
2             196371.67                      93875.14           Silver
3             108082.97                           NaN           Silver
4             180062.32                      80520.70             Gold

   Future_Balance
0      2227592.16
1      3282530.21
2      2005199.77
3      3674791.61
4      4847001.70

In [6]:
# Fill numerical columns with median
num_cols = df.select_dtypes(include=['float64', 'int64']).columns.drop('Future_Balance')
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

# Fill categorical column with mode
df['Customer_Segment'] = df['Customer_Segment'].fillna(df['Customer_Segment'].mode()[0])

In [8]:
# Winsorization for numerical features
for col in num_cols:
    lower = df[col].quantile(0.01)
    upper = df[col].quantile(0.99)
    df[col] = df[col].clip(lower, upper)

In [9]:
df = pd.get_dummies(df, columns=['Customer_Segment'], drop_first=True)

In [10]:
df

,Age,Annual_Income,Monthly_Expenses,Savings_Rate,Debt_to_Income_Ratio,Current_Investments_Value,Total_Loan_Amount,Avg_Credit_Score,Inflation_Rate,Interest_Rate,Years_of_Employment,Job_Stability_Score,Emergency_Fund_Value,Retirement_Fund_Contribution,Future_Balance,Customer_Segment_Gold,Customer_Segment_Silver
0,45.0,686081.81,17942.270,0.29,0.25,1807462.47,556913.97,651.0,6.69,6.65,9.4,0.39,67331.21,98811.48,2227592.16,False,False
1,40.0,796474.39,55385.200,0.12,0.55,2935502.53,563982.05,728.0,6.00,8.25,17.8,0.50,298162.24,42078.16,3282530.21,False,True
2,46.0,708707.11,41796.795,0.29,0.38,1569022.45,479932.78,748.0,6.14,7.33,8.5,0.44,196371.67,93875.14,2005199.77,False,True
3,55.0,940641.40,55378.160,0.11,0.18,3154348.23,484769.37,686.0,6.04,5.70,11.8,0.35,108082.97,88130.22,3674791.61,False,True
4,38.0,1452826.39,74823.600,0.29,0.75,4180505.40,839038.16,593.0,5.48,7.91,5.9,0.37,180062.32,80520.70,4847001.70,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,53.0,1051029.77,58774.730,0.27,0.59,2088030.29,911084.91,644.0,5.82,6.20,7.3,0.21,485067.43,146231.90,1414429.11,False,True
9996,21.0,1561405.09,78047.930,0.19,0.16,1741139.63,383488.72,743.0,5.21,8.08,10.8,0.24,199492.95,89405.63,2323362.66,False,True
9997,33.0,1047054.59,59624.070,0.16,0.13,1928311.13,354262.03,706.0,5.89,4.67,5.5,0.11,177635.32,109633.48,2210550.62,False,False
9998,45.0,1786130.19,83074.300,0.19,0.42,3311876.63,963452.55,691.0,7.95,7.49,4.9,0.01,199492.95,134198.97,4054716.69,True,False
9999,46.0,470796.92,23093.230,0.28,0.28,1388667.91,447909.66,675.0,6.28,7.94,6.5,0.05,97933.10,28774.96,1716924.73,False,True

In [11]:
# Target & features
X = df.drop('Future_Balance', axis=1)
y = df['Future_Balance']

In [12]:
X

,Age,Annual_Income,Monthly_Expenses,Savings_Rate,Debt_to_Income_Ratio,Current_Investments_Value,Total_Loan_Amount,Avg_Credit_Score,Inflation_Rate,Interest_Rate,Years_of_Employment,Job_Stability_Score,Emergency_Fund_Value,Retirement_Fund_Contribution,Customer_Segment_Gold,Customer_Segment_Silver
0,45.0,686081.81,17942.270,0.29,0.25,1807462.47,556913.97,651.0,6.69,6.65,9.4,0.39,67331.21,98811.48,False,False
1,40.0,796474.39,55385.200,0.12,0.55,2935502.53,563982.05,728.0,6.00,8.25,17.8,0.50,298162.24,42078.16,False,True
2,46.0,708707.11,41796.795,0.29,0.38,1569022.45,479932.78,748.0,6.14,7.33,8.5,0.44,196371.67,93875.14,False,True
3,55.0,940641.40,55378.160,0.11,0.18,3154348.23,484769.37,686.0,6.04,5.70,11.8,0.35,108082.97,88130.22,False,True
4,38.0,1452826.39,74823.600,0.29,0.75,4180505.40,839038.16,593.0,5.48,7.91,5.9,0.37,180062.32,80520.70,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,53.0,1051029.77,58774.730,0.27,0.59,2088030.29,911084.91,644.0,5.82,6.20,7.3,0.21,485067.43,146231.90,False,True
9996,21.0,1561405.09,78047.930,0.19,0.16,1741139.63,383488.72,743.0,5.21,8.08,10.8,0.24,199492.95,89405.63,False,True
9997,33.0,1047054.59,59624.070,0.16,0.13,1928311.13,354262.03,706.0,5.89,4.67,5.5,0.11,177635.32,109633.48,False,False
9998,45.0,1786130.19,83074.300,0.19,0.42,3311876.63,963452.55,691.0,7.95,7.49,4.9,0.01,199492.95,134198.97,True,False
9999,46.0,470796.92,23093.230,0.28,0.28,1388667.91,447909.66,675.0,6.28,7.94,6.5,0.05,97933.10,28774.96,False,True

In [13]:
y

0       2227592.16
1       3282530.21
2       2005199.77
3       3674791.61
4       4847001.70
           ...
9995    1414429.11
9996    2323362.66
9997    2210550.62
9998    4054716.69
9999    1716924.73
Name: Future_Balance, Length: 10000, dtype: float64

In [14]:
from sklearn.model_selection import train_test_split

# Split 80% train, 20% test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [17]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train_scaled, y_train)

LinearRegression()

In [18]:
from sklearn.metrics import r2_score, mean_squared_error

# Predict on test set
y_pred = lr.predict(X_test_scaled)

# Calculate R^2 score
r2 = r2_score(y_test, y_pred)

# Calculate Root Mean Squared Error (RMSE)
rmse = mean_squared_error(y_test, y_pred, squared=False)

print(f"R^2 Score: {r2:.4f}")
print(f"RMSE: {rmse:.2f}")

R^2 Score: 0.9491
RMSE: 268860.54

In [19]:
lr.score(X_test_scaled, y_test)

ValueError: Expected 2D array, got 1D array instead:
array=[2428754.53 2591620.35 6304224.54 ... 2319183.8  3846538.03 1871652.38].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.